CREATE TABLE IF NOT EXISTS user.users (
id       INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
name     VARCHAR(225) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO user.users (name) VALUES ('test');