clean:
	docker-compose down
build:
	docker-compose up -d --build
up:
	docker-compose up -d 
ps:
	docker-compose ps
stop:
	docker-compose stop
shell-app:
	docker-compose exec app  /bin/bash
logs-app:
	docker-compose logs app
